### ISSUE TITLE
Same as sideswitch?

### ISSUE THREAD

**Issue by jenstornell** [jongacnik/kirby-hidebar-field#1]
I made a field a few years ago. Is your field the same as this one?

https://github.com/jenstornell/kirby-sideswitch

**Comment by jongacnik** [comment]
@jenstornell nice, hadn't seen that! Similar, though this solution is geared towards hiding sidebar entirely (w/o the option to toggle it). I increasingly use Kirby as a headless api solution so have pages which are only containers for content, the content in the sidebar is not pertinent, and often confusing for content editors, in these instances. 

The plugins I write and release are solving specific needs for projects I work on, I publish them for the purpose of others perhaps finding them useful. Cheers 👌
